spring:
  application:
    name: ticketing-platform
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    # URL подключения к базе данных
    # Для Docker: jdbc:postgresql://postgres:5432/tickets (postgres - имя сервиса в docker-compose)
    # Для локального запуска: jdbc:postgresql://localhost:15432/tickets (15432 - внешний порт)
    url: ${DB_URL:jdbc:postgresql://localhost:15432/tickets}
    username: ${DB_USERNAME:ticket}
    password: ${DB_PASSWORD:ticket}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  mail:
    host: ${MAIL_HOST:smtp.timeweb.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:info@appticket.ru}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: ${MAIL_STARTTLS:true}
      mail.smtp.starttls.required: ${MAIL_STARTTLS:true}
      mail.smtp.ssl.enable: ${MAIL_SSL:false}
      mail.smtp.ssl.trust: ${MAIL_HOST:smtp.timeweb.ru}
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      add-mappings: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: INFO
    com.surnekev.ticketing: DEBUG
    com.surnekev.ticketing.security: DEBUG
    com.surnekev.ticketing.web.AdminConcertController: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    issuer: ticketing-platform
    access-token-ttl-seconds: ${JWT_TTL_SECONDS:1800}
    secret: ${JWT_SECRET:DeaukxWN9xJ5qe5AtwBOBDXgdJ13qEBPgf408F6EFjrXs2H/Bc9LkeAKCA+SjFBL}

admin:
  default-password: ${ADMIN_DEFAULT_PASSWORD:12345}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:8473237302:AAExIgw36kE1M1A9QTzuYW1sCwFaCffyKog}
  manager-chat-id: ${TELEGRAM_CHAT_ID:836633923}

seatmap:
  hold-ttl-seconds: 1800

mail:
  from: ${MAIL_FROM:info@appticket.ru}

file:
  upload:
    directory: ${FILE_UPLOAD_DIR:uploads}
    base-url: ${FILE_UPLOAD_BASE_URL:/uploads}
